### ISSUE TITLE
Wordpress Footer 

### ISSUE THREAD

**Issue by SamihaHassan** [CodetheChangeFoundation/wordpress-theme-starter#3]

**Comment by ArielleMurad** [comment]
We want to create a footer identical to the one in this [link to the mock-up](https://www.figma.com/file/fAhXbCJw45AXqV3BOkqLdl1P/Vancouver-Tenants-Union?node-id=44%3A64) (specifications are in the mock-up). Create using the footer.php file in [repo](https://github.com/CodetheChangeFoundation/tenants-union) .
